import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Software Engineer & Open Source Contributor - Pradip Chaudhary",
  description:
    "Pradip Chaudhary is a passionate software engineer and dedicated open-source contributor, driven by a relentless pursuit of excellence in technology. With a strong background in software development, Pradip brings a wealth of expertise in building robust and scalable applications. He is committed to the principles of open-source software, actively contributing to various projects and communities to foster collaboration and innovation. Through his contributions, Pradip strives to make meaningful impacts in the world of technology, empowering others and advancing the boundaries of what's possible. This metadata was generated by create next app.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta
          name="description"
          content="Pradip Chaudhary - Software Engineer & Open Source Contributor. Learn about my work, projects, and contributions to the open-source community."
        />
        <meta
          name="keywords"
          content="Pradip Chaudhary, Software Engineer, Open Source Contributor, Web Developer, Portfolio, JavaScript Developer, React Developer, Node.js Developer, Full Stack Developer, Software Development Projects, GitHub Portfolio, Web Development Portfolio, Programming Portfolio, Tech Portfolio, Code Portfolio, Developer Portfolio, Technology Projects, Coding Projects"
        />

        <meta name="author" content="Pradip Chaudhary" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="robots" content="index, follow" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta
          property="og:title"
          content="Pradip Chaudhary - Software Engineer & Open Source Contributor"
        />
        <meta
          property="og:description"
          content="Pradip Chaudhary - Software Engineer & Open Source Contributor. Learn about my work, projects, and contributions to the open-source community."
        />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://pradipchaudhary.com.np/" />
        <meta
          property="og:image"
          content="https://pradipchaudhary.com.np/images/your-image.jpg"
        />
        <meta name="twitter:card" content="summary_large_image" />
        <meta
          name="twitter:title"
          content="Pradip Chaudhary - Software Engineer & Open Source Contributor"
        />
        <meta
          name="twitter:description"
          content="Pradip Chaudhary - Software Engineer & Open Source Contributor. Learn about my work, projects, and contributions to the open-source community."
        />
        <meta
          name="twitter:image"
          content="https://pradipchaudhary.com.np/images/your-image.jpg"
        />
        <title>
          Pradip Chaudhary - Software Engineer & Open Source Contributor
        </title>
        <link rel="canonical" href="https://pradipchaudhary.com.np/" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
